import type { WheelPrize } from "@/types/lucky-wheel"

export const wheelPrizes: WheelPrize[] = [
  {
    id: "coins-20m",
    type: "coins",
    amount: 20000000,
    label: "20M",
    icon: "💰",
    rarity: "rare",
  },
  {
    id: "coins-5m",
    type: "coins",
    amount: 5000000,
    label: "5M",
    icon: "💰",
    rarity: "common",
  },
  {
    id: "coins-100m",
    type: "coins",
    amount: 100000000,
    label: "100M",
    icon: "💰",
    rarity: "legendary",
  },
  {
    id: "free-spin",
    type: "special",
    amount: 1,
    label: "FREE",
    icon: "🎁",
    rarity: "epic",
  },
  {
    id: "coins-10m",
    type: "coins",
    amount: 10000000,
    label: "10M",
    icon: "💰",
    rarity: "common",
  },
  {
    id: "big-prize",
    type: "special",
    amount: 500000000,
    label: "BIG",
    icon: "🎰",
    rarity: "legendary",
  },
  {
    id: "coins-50m",
    type: "coins",
    amount: 50000000,
    label: "50M",
    icon: "💰",
    rarity: "epic",
  },
  {
    id: "coins-1m",
    type: "coins",
    amount: 1000000,
    label: "1M",
    icon: "💰",
    rarity: "common",
  },
  {
    id: "coins-3m",
    type: "coins",
    amount: 3000000,
    label: "3M",
    icon: "💰",
    rarity: "common",
  },
  {
    id: "coins-2m",
    type: "coins",
    amount: 2000000,
    label: "2M",
    icon: "💰",
    rarity: "common",
  },
  {
    id: "coins-1m-2",
    type: "coins",
    amount: 1000000,
    label: "1M",
    icon: "💰",
    rarity: "common",
  },
  {
    id: "coins-1m-3",
    type: "coins",
    amount: 1000000,
    label: "1M",
    icon: "💰",
    rarity: "common",
  },
]
